name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Backend & Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install and Build Frontend
        run: |
          npm ci
          npm run build

  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql

      - name: Copy .env and configure DB
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_DATABASE=testing" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Install Composer dev dependencies
        run: composer install
      
      - name: Wait for MySQL to be ready
        run: sleep 15

      - name: Run Laravel Migrations
        run: |
          php artisan key:generate && 
          php artisan db:show && 
          php artisan migrate --force 

      - name: Run Tests
        run: php artisan test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
            cd ${{ vars.DEPLOY_PATH }}
            export APP_KEY=${{ secrets.APP_KEY }}
            export APP_URL=${{ vars.APP_URL }}
            export DB_DATABASE=${{ vars.DB_DATABASE }}
            export DB_USERNAME=${{ vars.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DEFAULT_ADMIN_PASSWORD=${{ secrets.DEFAULT_ADMIN_PASSWORD }}
            export DEFAULT_API_PASSWORD=${{ secrets.DEFAULT_API_PASSWORD }}
            bash ./setup-env.sh
            chmod +x deploy.sh
            bash ./deploy.sh
          EOF
